//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Registation_Form.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    
    public partial class Company
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Company()
        {
            this.Workers = new HashSet<Worker>();
        }
        
        public int Id { get; set; }
        [DisplayName("Company name")]
        public string Name { get; set; }
        [DisplayName("Company size")]
        public Nullable<int> CompanySize { get; set; }
        [DisplayName("Legal Status")]
        public string LegalStatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Worker> Workers { get; set; }
    }
}
