//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Registation_Form.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    
    public partial class Worker
    {
        [DisplayName("Id")]
        public int Id { get; set; }
        [DisplayName("Surname")]
        public string Surname { get; set; }
        [DisplayName("Name")]
        public string Name { get; set; }
        [DisplayName("Middle name")]
        public string MiddleName { get; set; }
        [DisplayName("Hiring day")]
        public string HiringDay { get; set; }
        [DisplayName("Position")]
        public string Position { get; set; }
        [DisplayName("Company")]
        public Nullable<int> CompanyId { get; set; }
    
        public virtual Company Company { get; set; }
    }
}
